graph TD;
    "UnboundControlBControlBindingModel"-->"UnboundControlAControlBindingModel";
    "ControlBControlBindingModel"-->"UnboundControlBControlBindingModel";
    "ControlAControlBindingModel"-->"UnboundControlAControlBindingModel";
	"UnboundControlAControlBindingModel"-->"PlatformBaseControlBindingModel";
