graph TD
    [Nuget Package Restore]
    [sonar scanner start]
    [dotnet build]
    [dotnet test]
    [sonar scanner stop]
    [check test coverage percentage]
    [check for outdated packages]
    [check for dependencies that can be simplified]
    [check for unused dependencies]
